# Generated by Django 4.2.24 on 2026-05-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="التاريخ")),
                (
                    "new_graduates",
                    models.IntegerField(default=0, verbose_name="خريجون جدد"),
                ),
                (
                    "new_employers",
                    models.IntegerField(default=0, verbose_name="أصحاب عمل جدد"),
                ),
                (
                    "new_jobs",
                    models.IntegerField(default=0, verbose_name="وظائف جديدة"),
                ),
                (
                    "applications",
                    models.IntegerField(default=0, verbose_name="تقديم وظائف"),
                ),
                (
                    "profile_views",
                    models.IntegerField(default=0, verbose_name="مشاهدات الملفات"),
                ),
                (
                    "searches",
                    models.IntegerField(default=0, verbose_name="عمليات البحث"),
                ),
                ("interviews", models.IntegerField(default=0, verbose_name="مقابلات")),
                ("hirings", models.IntegerField(default=0, verbose_name="توظيف")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "إحصاء يومي",
                "verbose_name_plural": "الإحصاءات اليومية",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PlatformEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=100, verbose_name="نوع الحدث"),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "data",
                    models.JSONField(blank=True, null=True, verbose_name="البيانات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "حدث منصة",
                "verbose_name_plural": "أحداث المنصة",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_users", models.IntegerField(default=0)),
                ("total_graduates", models.IntegerField(default=0)),
                ("total_employers", models.IntegerField(default=0)),
                ("total_companies", models.IntegerField(default=0)),
                ("total_jobs", models.IntegerField(default=0)),
                ("total_applications", models.IntegerField(default=0)),
                ("total_hires", models.IntegerField(default=0)),
                ("verified_graduates", models.IntegerField(default=0)),
                ("verified_companies", models.IntegerField(default=0)),
                ("active_jobs", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ملخص إحصائي",
                "verbose_name_plural": "ملخص إحصائي",
            },
        ),
    ]
