# Generated by Django 4.2.24 on 2026-05-21 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=255, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="الاسم (إنجليزي)",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="الأيقونة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "قطاع",
                "verbose_name_plural": "القطاعات",
                "ordering": ["name_ar"],
            },
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="اسم الشركة"),
                ),
                (
                    "company_name_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="اسم الشركة (إنجليزي)",
                    ),
                ),
                (
                    "commercial_registration",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="السجل التجاري"
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("1-10", "1-10 موظف"),
                            ("11-50", "11-50 موظف"),
                            ("51-200", "51-200 موظف"),
                            ("201-1000", "201-1000 موظف"),
                            ("1000+", "أكثر من 1000 موظف"),
                        ],
                        default="11-50",
                        max_length=20,
                        verbose_name="حجم الشركة",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, null=True, verbose_name="الموقع الإلكتروني"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company_logos/",
                        verbose_name="الشعار",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company_covers/",
                        verbose_name="صورة الغلاف",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="وصف الشركة"),
                ),
                ("city", models.CharField(max_length=255, verbose_name="المدينة")),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="العنوان"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="رابط LinkedIn"
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط Twitter"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="موثقة"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التوثيق"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="مميزة"),
                ),
                (
                    "profile_views",
                    models.IntegerField(default=0, verbose_name="عدد المشاهدات"),
                ),
                (
                    "total_jobs",
                    models.IntegerField(default=0, verbose_name="إجمالي الوظائف"),
                ),
                (
                    "total_hires",
                    models.IntegerField(default=0, verbose_name="إجمالي التوظيف"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "industry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to="employers.industry",
                        verbose_name="القطاع",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف شركة",
                "verbose_name_plural": "ملفات الشركات",
            },
        ),
        migrations.CreateModel(
            name="HRTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "مدير"),
                            ("recruiter", "مسؤول توظيف"),
                            ("viewer", "مشاهد"),
                        ],
                        default="recruiter",
                        max_length=50,
                        verbose_name="الدور",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_team",
                        to="employers.companyprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "عضو فريق HR",
                "verbose_name_plural": "فريق الموارد البشرية",
                "unique_together": {("company", "user")},
            },
        ),
        migrations.CreateModel(
            name="CompanyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="التقييم",
                    ),
                ),
                (
                    "review",
                    models.TextField(blank=True, null=True, verbose_name="المراجعة"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="معتمدة"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="employers.companyprofile",
                    ),
                ),
                (
                    "graduate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم شركة",
                "verbose_name_plural": "تقييمات الشركات",
                "unique_together": {("company", "graduate")},
            },
        ),
        migrations.AddIndex(
            model_name="companyprofile",
            index=models.Index(
                fields=["city", "industry"], name="employers_c_city_2a1d5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyprofile",
            index=models.Index(
                fields=["is_verified", "is_featured"],
                name="employers_c_is_veri_33a1a4_idx",
            ),
        ),
    ]
