# Generated by Django 4.2.24 on 2026-05-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("image_url", models.URLField(blank=True, verbose_name="رابط الصورة")),
                ("link_url", models.URLField(blank=True, verbose_name="رابط الإعلان")),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("small", "صغير"),
                            ("medium", "متوسط"),
                            ("large", "كبير"),
                            ("sidebar", "شريط جانبي"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="المكان",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "click_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد النقرات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "إعلان",
                "verbose_name_plural": "الإعلانات",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
