# Generated by Django 4.2.24 on 2026-05-21 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=255, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="الاسم (إنجليزي)",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="الكود"),
                ),
                ("city", models.CharField(max_length=255, verbose_name="المدينة")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "كلية",
                "verbose_name_plural": "الكليات",
                "ordering": ["name_ar"],
            },
        ),
        migrations.CreateModel(
            name="GraduateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="العنوان المهني",
                    ),
                ),
                (
                    "graduation_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="سنة التخرج"
                    ),
                ),
                (
                    "major",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="التخصص"
                    ),
                ),
                (
                    "gpa",
                    models.FloatField(blank=True, null=True, verbose_name="المعدل"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="المدينة"
                    ),
                ),
                (
                    "is_employed",
                    models.BooleanField(default=False, verbose_name="موظف حالياً"),
                ),
                (
                    "current_company",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="الشركة الحالية",
                    ),
                ),
                (
                    "current_position",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="المنصب الحالي",
                    ),
                ),
                (
                    "available_for_work",
                    models.BooleanField(default=True, verbose_name="متاح للعمل"),
                ),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="الراتب المتوقع",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="رابط LinkedIn"
                    ),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط GitHub"),
                ),
                (
                    "portfolio_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="رابط Portfolio"
                    ),
                ),
                (
                    "behance_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط Behance"),
                ),
                (
                    "profile_views",
                    models.IntegerField(default=0, verbose_name="عدد المشاهدات"),
                ),
                (
                    "search_appearances",
                    models.IntegerField(default=0, verbose_name="ظهور في البحث"),
                ),
                (
                    "employer_interactions",
                    models.IntegerField(default=0, verbose_name="تفاعلات أصحاب العمل"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاكتمال"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graduates",
                        to="graduates.college",
                        verbose_name="الكلية",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف خريج",
                "verbose_name_plural": "ملفات الخريجين",
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=255, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="الاسم (إنجليزي)",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="الأيقونة"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="الترتيب")),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="graduates.skillcategory",
                        verbose_name="التصنيف الأب",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصنيف المهارات",
                "verbose_name_plural": "تصنيفات المهارات",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=255, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="الاسم (إنجليزي)",
                    ),
                ),
                (
                    "demand_score",
                    models.FloatField(default=0.0, verbose_name="معدل الطلب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skills",
                        to="graduates.skillcategory",
                        verbose_name="التصنيف",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهارة",
                "verbose_name_plural": "المهارات",
                "ordering": ["name_ar"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="عنوان المشروع"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="التقنيات المستخدمة",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="الرابط")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/",
                        verbose_name="الصورة",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ البداية"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ النهاية"
                    ),
                ),
                (
                    "is_ongoing",
                    models.BooleanField(default=False, verbose_name="مستمر"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "graduate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="graduates.graduateprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشروع",
                "verbose_name_plural": "المشاريع",
                "ordering": ["-start_date", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProfileView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "graduate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_views_log",
                        to="graduates.graduateprofile",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "مشاهدة ملف",
                "verbose_name_plural": "مشاهدات الملفات",
            },
        ),
        migrations.CreateModel(
            name="GraduateSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("beginner", "مبتدئ"),
                            ("intermediate", "متوسط"),
                            ("advanced", "متقدم"),
                            ("expert", "خبير"),
                        ],
                        default="intermediate",
                        max_length=20,
                        verbose_name="المستوى",
                    ),
                ),
                (
                    "years_experience",
                    models.IntegerField(default=0, verbose_name="سنوات الخبرة"),
                ),
                (
                    "is_top_skill",
                    models.BooleanField(default=False, verbose_name="مهارة رئيسية"),
                ),
                (
                    "graduate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graduates.graduateprofile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graduates.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهارة الخريج",
                "verbose_name_plural": "مهارات الخريجين",
                "unique_together": {("graduate", "skill")},
            },
        ),
        migrations.AddField(
            model_name="graduateprofile",
            name="skills",
            field=models.ManyToManyField(
                related_name="graduates",
                through="graduates.GraduateSkill",
                to="graduates.skill",
                verbose_name="المهارات",
            ),
        ),
        migrations.AddField(
            model_name="graduateprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graduate_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="المسمى الوظيفي"),
                ),
                ("company", models.CharField(max_length=255, verbose_name="الشركة")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="الموقع"
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "دوام كامل"),
                            ("part_time", "دوام جزئي"),
                            ("freelance", "حر"),
                            ("internship", "تدريب"),
                            ("contract", "عقد"),
                        ],
                        default="full_time",
                        max_length=50,
                        verbose_name="نوع الوظيفة",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ النهاية"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="حالياً"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "graduate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience",
                        to="graduates.graduateprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "خبرة",
                "verbose_name_plural": "الخبرات",
                "ordering": ["-start_date", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree",
                    models.CharField(max_length=255, verbose_name="الدرجة العلمية"),
                ),
                (
                    "field_of_study",
                    models.CharField(max_length=255, verbose_name="مجال الدراسة"),
                ),
                (
                    "institution",
                    models.CharField(max_length=255, verbose_name="المؤسسة التعليمية"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="البلد"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ النهاية"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="حالياً"),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="التقدير"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "graduate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="graduates.graduateprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "المؤهل التعليمي",
                "verbose_name_plural": "المؤهلات التعليمية",
                "ordering": ["-end_date", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="السيرة الذاتية", max_length=255, verbose_name="العنوان"
                    ),
                ),
                ("file", models.FileField(upload_to="cvs/", verbose_name="الملف")),
                (
                    "language",
                    models.CharField(
                        choices=[("ar", "العربية"), ("en", "English")],
                        default="ar",
                        max_length=10,
                        verbose_name="اللغة",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "is_parsed",
                    models.BooleanField(default=False, verbose_name="تم التحليل"),
                ),
                (
                    "parsed_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="بيانات التحليل"
                    ),
                ),
                ("file_size", models.IntegerField(default=0, verbose_name="حجم الملف")),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="نوع الملف"
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="عدد التحميلات"),
                ),
                (
                    "graduate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvs",
                        to="graduates.graduateprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "السيرة الذاتية",
                "verbose_name_plural": "السير الذاتية",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم الشهادة")),
                (
                    "issuer",
                    models.CharField(max_length=255, verbose_name="الجهة المانحة"),
                ),
                ("issue_date", models.DateField(verbose_name="تاريخ الإصدار")),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="رقم الاعتماد",
                    ),
                ),
                (
                    "credential_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط التحقق"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certifications/",
                        verbose_name="الملف",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="موثقة"),
                ),
                (
                    "graduate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="graduates.graduateprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "شهادة",
                "verbose_name_plural": "الشهادات",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="SavedGraduate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_graduates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "graduate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="graduates.graduateprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "خريج محفوظ",
                "verbose_name_plural": "الخريجين المحفوظين",
                "unique_together": {("employer", "graduate")},
            },
        ),
        migrations.AddIndex(
            model_name="graduateprofile",
            index=models.Index(
                fields=["college", "graduation_year"],
                name="graduates_g_college_5277ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="graduateprofile",
            index=models.Index(
                fields=["city", "available_for_work"],
                name="graduates_g_city_2fe3c1_idx",
            ),
        ),
    ]
