# Generated by Django 4.2.24 on 2026-05-21 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityStreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0, verbose_name="المواظبة الحالية"
                    ),
                ),
                (
                    "longest_streak",
                    models.PositiveIntegerField(default=0, verbose_name="أطول مواظبة"),
                ),
                (
                    "total_activities",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي النشاطات"
                    ),
                ),
                (
                    "last_active_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="آخر تاريخ نشاط"
                    ),
                ),
                (
                    "streak_history",
                    models.JSONField(
                        blank=True, default=list, verbose_name="سجل المواظبة"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_streak",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "مواظبة النشاط",
                "verbose_name_plural": "مواظبات النشاط",
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "تسجيل دخول"),
                            ("apply_job", "تقديم على وظيفة"),
                            ("update_profile", "تحديث الملف الشخصي"),
                            ("add_skill", "إضافة مهارة"),
                            ("view_job", "عرض وظيفة"),
                            ("send_message", "إرسال رسالة"),
                            ("create_job", "إنشاء وظيفة"),
                            ("interview", "مقابلة"),
                            ("save_job", "حفظ وظيفة"),
                        ],
                        max_length=30,
                        verbose_name="نوع النشاط",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="الوصف"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات إضافية"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ النشاط"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل نشاط",
                "verbose_name_plural": "سجلات النشاط",
                "ordering": ["-created_at"],
            },
        ),
    ]
