# Generated by Django 4.2.24 on 2026-06-02 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_activitystreak_activitylog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitystreak",
            name="user",
        ),
        migrations.DeleteModel(
            name="ActivityLog",
        ),
        migrations.DeleteModel(
            name="ActivityStreak",
        ),
    ]
