# Generated by Django 4.2.24 on 2026-05-21 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employers", "0001_initial"),
        ("graduates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=255, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="الاسم (إنجليزي)",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="الأيقونة"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="الترتيب")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "تصنيف وظيفي",
                "verbose_name_plural": "التصنيفات الوظيفية",
                "ordering": ["sort_order", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="المسمى الوظيفي"),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "requirements",
                    models.TextField(blank=True, null=True, verbose_name="المتطلبات"),
                ),
                (
                    "responsibilities",
                    models.TextField(blank=True, null=True, verbose_name="المسؤوليات"),
                ),
                (
                    "benefits",
                    models.TextField(blank=True, null=True, verbose_name="المزايا"),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "دوام كامل"),
                            ("part_time", "دوام جزئي"),
                            ("freelance", "حر"),
                            ("contract", "عقد"),
                            ("internship", "تدريب"),
                            ("remote", "عن بعد"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="نوع التوظيف",
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "مبتدئ"),
                            ("junior", "مبتدئ مع خبرة"),
                            ("mid", "متوسط"),
                            ("senior", "كبير"),
                            ("lead", "قائد فريق"),
                            ("executive", "تنفيذي"),
                        ],
                        default="mid",
                        max_length=20,
                        verbose_name="مستوى الخبرة",
                    ),
                ),
                (
                    "years_experience_min",
                    models.IntegerField(
                        default=0, verbose_name="الحد الأدنى لسنوات الخبرة"
                    ),
                ),
                (
                    "years_experience_max",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="الحد الأقصى لسنوات الخبرة"
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="الحد الأدنى للراتب",
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="الحد الأقصى للراتب",
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(
                        default="LYD", max_length=10, verbose_name="عملة الراتب"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="المدينة"
                    ),
                ),
                (
                    "is_remote",
                    models.BooleanField(default=False, verbose_name="عن بعد"),
                ),
                (
                    "vacancies",
                    models.IntegerField(default=1, verbose_name="عدد الوظائف الشاغرة"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("active", "منشورة"),
                            ("paused", "موقفة"),
                            ("closed", "مغلقة"),
                            ("filled", "تم التوظيف"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="مميزة"),
                ),
                ("is_urgent", models.BooleanField(default=False, verbose_name="عاجلة")),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="عدد المشاهدات"),
                ),
                (
                    "applications_count",
                    models.IntegerField(default=0, verbose_name="عدد المتقدمين"),
                ),
                (
                    "shortlisted_count",
                    models.IntegerField(default=0, verbose_name="عدد المرشحين"),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر موعد للتقديم"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ النشر"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإغلاق"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="jobs.jobcategory",
                        verbose_name="التصنيف",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_jobs",
                        to="employers.companyprofile",
                        verbose_name="الشركة",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ناشر الوظيفة",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        related_name="job_posts",
                        to="graduates.skill",
                        verbose_name="المهارات المطلوبة",
                    ),
                ),
                (
                    "targeted_colleges",
                    models.ManyToManyField(
                        blank=True,
                        related_name="targeted_jobs",
                        to="graduates.college",
                        verbose_name="الكليات المستهدفة",
                    ),
                ),
            ],
            options={
                "verbose_name": "وظيفة",
                "verbose_name_plural": "الوظائف",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(
                        blank=True, null=True, verbose_name="خطاب التقديم"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("reviewed", "تمت المراجعة"),
                            ("shortlisted", "مدرج في القائمة المختصرة"),
                            ("interview", "مقابلة"),
                            ("accepted", "مقبول"),
                            ("rejected", "مرفوض"),
                            ("withdrawn", "منسحب"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "employer_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات صاحب العمل"
                    ),
                ),
                (
                    "match_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="نسبة المطابقة"
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المتقدم",
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="graduates.cv",
                        verbose_name="السيرة الذاتية",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.jobpost",
                        verbose_name="الوظيفة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقديم وظيفة",
                "verbose_name_plural": "تقديم الوظائف",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("phone", "هاتفي"),
                            ("video", "فيديو"),
                            ("in_person", "حضوري"),
                            ("technical", "تقني"),
                        ],
                        default="video",
                        max_length=20,
                        verbose_name="نوع المقابلة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "مجدولة"),
                            ("confirmed", "مؤكدة"),
                            ("completed", "مكتملة"),
                            ("cancelled", "ملغية"),
                            ("rescheduled", "معاد جدولتها"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="موعد المقابلة")),
                (
                    "duration_minutes",
                    models.IntegerField(default=30, verbose_name="المدة (دقيقة)"),
                ),
                (
                    "location",
                    models.TextField(
                        blank=True, null=True, verbose_name="الموقع / الرابط"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="التقييم"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="jobs.jobapplication",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "scheduled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_interviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المجدول بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقابلة",
                "verbose_name_plural": "المقابلات",
            },
        ),
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="jobs.jobpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "وظيفة محفوظة",
                "verbose_name_plural": "الوظائف المحفوظة",
                "unique_together": {("user", "job")},
            },
        ),
        migrations.AddIndex(
            model_name="jobpost",
            index=models.Index(
                fields=["status", "employment_type"],
                name="jobs_jobpos_status_ae4fce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobpost",
            index=models.Index(
                fields=["company", "status"], name="jobs_jobpos_company_b5af56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobpost",
            index=models.Index(
                fields=["city", "experience_level"], name="jobs_jobpos_city_341ea8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("job", "applicant")},
        ),
    ]
