# Generated by Django 4.2.24 on 2026-06-03 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_ar", models.CharField(max_length=100)),
                ("order", models.IntegerField()),
                ("color", models.CharField(default="#3b82f6", max_length=7)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "مرحلة التوظيف",
                "verbose_name_plural": "مراحل التوظيف",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Scorecard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("max_score", models.IntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecards",
                        to="jobs.jobpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "بطاقة تقييم",
                "verbose_name_plural": "بطاقات التقييم",
            },
        ),
        migrations.CreateModel(
            name="ScorecardCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_ar", models.CharField(max_length=200)),
                ("max_points", models.IntegerField(default=10)),
                ("weight", models.FloatField(default=1.0)),
                ("order", models.IntegerField(default=0)),
                (
                    "scorecard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="jobs.scorecard",
                    ),
                ),
            ],
            options={
                "verbose_name": "معيار تقييم",
                "verbose_name_plural": "معايير التقييم",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ScorecardResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.FloatField(default=0)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecard_results",
                        to="jobs.jobapplication",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scorecard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="jobs.scorecard"
                    ),
                ),
            ],
            options={
                "verbose_name": "نتيجة تقييم",
                "verbose_name_plural": "نتائج التقييم",
            },
        ),
        migrations.CreateModel(
            name="ScorecardCriterionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("comment", models.TextField(blank=True)),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="jobs.scorecardcriterion",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="jobs.scorecardresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "درجة معيار",
                "verbose_name_plural": "درجات المعايير",
            },
        ),
        migrations.CreateModel(
            name="ApplicationStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_stage",
                        to="jobs.jobapplication",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="jobs.pipelinestage",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرحلة المتقدم",
                "verbose_name_plural": "مراحل المتقدمين",
            },
        ),
    ]
