# Generated by Django 4.2.30 on 2026-06-03 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(max_length=255, verbose_name="اسم المؤسسة"),
                ),
                (
                    "institution_name_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="اسم المؤسسة (إنجليزي)",
                    ),
                ),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("university", "جامعة"),
                            ("college", "كلية"),
                            ("institute", "معهد"),
                            ("school", "مدرسة"),
                            ("training_center", "مركز تدريب"),
                        ],
                        default="university",
                        max_length=30,
                        verbose_name="نوع المؤسسة",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="institution_logos/",
                        verbose_name="الشعار",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="institution_covers/",
                        verbose_name="صورة الغلاف",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="رقم الترخيص"
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, null=True, verbose_name="الموقع الإلكتروني"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="العنوان"),
                ),
                ("city", models.CharField(max_length=255, verbose_name="المدينة")),
                (
                    "country",
                    models.CharField(
                        default="المملكة العربية السعودية",
                        max_length=255,
                        verbose_name="الدولة",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "student_count",
                    models.IntegerField(default=0, verbose_name="عدد الطلاب"),
                ),
                (
                    "graduate_count",
                    models.IntegerField(
                        default=0, verbose_name="عدد الخريجين المسجلين"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="موثقة"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التوثيق"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف المؤسسة",
                "verbose_name_plural": "ملفات المؤسسات",
            },
        ),
        migrations.CreateModel(
            name="InstitutionPartnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partnership_type",
                    models.CharField(
                        choices=[
                            ("recruitment", "توظيف"),
                            ("training", "تدريب"),
                            ("research", "بحث علمي"),
                            ("sponsorship", "رعاية"),
                        ],
                        default="recruitment",
                        max_length=30,
                        verbose_name="نوع الشراكة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("active", "نشط"),
                            ("completed", "مكتمل"),
                            ("terminated", "منتهي"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "agreement_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="partnership_agreements/",
                        verbose_name="ملف الاتفاقية",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ البداية"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ النهاية"
                    ),
                ),
                (
                    "contact_person_name",
                    models.CharField(max_length=255, verbose_name="اسم جهة الاتصال"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_partnerships",
                        to="employers.companyprofile",
                        verbose_name="الشركة",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerships",
                        to="institution.institutionprofile",
                        verbose_name="المؤسسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "شراكة مؤسسة",
                "verbose_name_plural": "الشراكات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GraduateTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(max_length=100, verbose_name="الرقم الجامعي"),
                ),
                ("major", models.CharField(max_length=255, verbose_name="التخصص")),
                (
                    "college",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="الكلية"
                    ),
                ),
                ("enrollment_year", models.IntegerField(verbose_name="سنة الالتحاق")),
                (
                    "graduation_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="سنة التخرج"
                    ),
                ),
                (
                    "gpa",
                    models.FloatField(blank=True, null=True, verbose_name="المعدل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "ملتحق"),
                            ("graduated", "متخرج"),
                            ("withdrew", "منسحب"),
                            ("suspended", "موقوف"),
                        ],
                        default="enrolled",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "is_employed",
                    models.BooleanField(default=False, verbose_name="موظف"),
                ),
                (
                    "employment_details",
                    models.JSONField(
                        blank=True, null=True, verbose_name="تفاصيل التوظيف"
                    ),
                ),
                (
                    "last_contact_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="آخر تاريخ تواصل"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "graduate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_tracking",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الخريج",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_graduates",
                        to="institution.institutionprofile",
                        verbose_name="المؤسسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تتبع الخريج",
                "verbose_name_plural": "تتبع الخريجين",
            },
        ),
        migrations.CreateModel(
            name="CurriculumFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_name",
                    models.CharField(max_length=255, verbose_name="اسم البرنامج"),
                ),
                (
                    "course_name",
                    models.CharField(max_length=255, verbose_name="اسم المقرر"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="التقييم",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="الملاحظات"),
                ),
                (
                    "relevance_to_job",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                        verbose_name="ملاءمة لسوق العمل",
                    ),
                ),
                (
                    "skills_acquired",
                    models.JSONField(
                        blank=True, null=True, verbose_name="المهارات المكتسبة"
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="عام")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "graduate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_feedback",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الخريج",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_feedback",
                        to="institution.institutionprofile",
                        verbose_name="المؤسسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم المناهج",
                "verbose_name_plural": "تقييمات المناهج",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="institutionprofile",
            index=models.Index(
                fields=["city", "institution_type"], name="institution_city_2cf867_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institutionprofile",
            index=models.Index(
                fields=["is_verified"], name="institution_is_veri_d2bb12_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="institutionpartnership",
            unique_together={("institution", "company")},
        ),
        migrations.AddIndex(
            model_name="graduatetracking",
            index=models.Index(
                fields=["institution", "status"], name="institution_institu_254253_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="graduatetracking",
            index=models.Index(
                fields=["institution", "graduation_year"],
                name="institution_institu_f88376_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="graduatetracking",
            unique_together={("institution", "student_id")},
        ),
        migrations.AlterUniqueTogether(
            name="curriculumfeedback",
            unique_together={("graduate", "course_name")},
        ),
    ]
