# Generated by Django 4.2.30 on 2026-06-03 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("institution", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graduatetracking",
            name="graduate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institution_tracking",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الخريج",
            ),
        ),
    ]
